openapi: "3.1.0"
info:
  title: API de Productos
  version: "1.0"
paths:
  /api/productos/todos:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Lista de productos obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
  
    
  
