openapi: "3.1.0"
info:
  title: API de Productos
  version: "1.0"
paths:
  /api/carrito:
    get:
      summary: Obtiene todos los carritos
      tags:
        - Carritos
      responses:
        "200":
          description: Lista de carritos obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Carrito"
    post:
      summary: Crea un nuevo carrito
      tags:
        - Carritos
      requestBody:
        description: Datos del carrito a crear
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Carrito"
      responses:
        "201":
          description: Carrito creado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Carrito"
  /api/carrito/{idc}/{idp}: 
    post:
      summary: Agrega un producto a un carrito
      tags:
        - Carritos
      parameters:
        - in: path
          name: idc
          description: ID del carrito
          required: true
          schema:
            type: string
        - in: path
          name: idp
          description: ID del producto a agregar
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Producto agregado exitosamente al carrito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Carrito"
    delete:
      summary: Elimina un producto de un carrito
      tags:
        - Carritos
      parameters:
        - in: path
          name: idc
          description: ID del carrito
          required: true
          schema:
            type: string
        - in: path
          name: idp
          description: ID del producto a eliminar
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Producto eliminado exitosamente del carrito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Carrito"
  /api/carrito/{idc}/crear-ticket:
    post:
      summary: Crea un ticket a partir de un carrito
      tags:
        - Carritos
      parameters:
        - in: path
          name: idc
          description: ID del carrito
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Ticket creado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ticket"

components:
  schemas:
    Carrito:
      type: object
      properties:
        // creacion de un carrito que deja ingresar productos por medio de los ID de los dos.
    Ticket:
      type: object
      properties:
        // definición de las propiedades del ticket
